//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB0702_XPath
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductJIB
    {
        public int Pid { get; set; }
        public string ProductName { get; set; }
        public string Detail { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
